import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './Components/Footer.jsx'
import NavBar from './Components/NavBar'
import './Components/components.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}        
        <Footer />
      </body>
    </html>
  )
}


